export const successCodes = {
  OK: "OK", 
  CREATED: "CREATED",
  ACCEPTED: "ACCEPTED", 
  NON_AUTHORITATIVE_INFORMATION: "NON_AUTHORITATIVE_INFORMATION", 
  NO_CONTENT: "NO_CONTENT", 
  RESET_CONTENT: "RESET_CONTENT", 
  PARTIAL_CONTENT: "PARTIAL_CONTENT", 
  MULTI_STATUS: "MULTI_STATUS",
  ALREADY_REPORTED: "ALREADY_REPORTED", 
  IM_USED: "IM_USED",
} as const;